import type { Perfume } from "./types";

export const DB: Perfume[] = [
  { id: "1", name: "Miss Dior Blooming Bouquet", brand: "Dior", price: 110, pr: "$$", notes: ["peony", "rose", "white musk", "damask rose"], accords: ["floral", "fresh", "powdery", "musky"], rating: 4.3, reviews: 2847, review: "Like walking through a garden in spring \u2014 elegant without trying too hard.", img: "https://fimgs.net/mdimg/perfume/375x500.25808.jpg", sillage: "soft" },
  { id: "2", name: "Black Opium", brand: "Yves Saint Laurent", price: 142, pr: "$$", notes: ["coffee", "vanilla", "white flowers", "cedar"], accords: ["warm spicy", "sweet", "vanilla", "gourmand"], rating: 4.5, reviews: 5621, review: "Addictive and bold \u2014 confidence in a bottle.", img: "https://fimgs.net/mdimg/perfume/375x500.25324.jpg", sillage: "strong" },
  { id: "3", name: "Baccarat Rouge 540", brand: "Maison Francis Kurkdjian", price: 325, pr: "$$$", notes: ["saffron", "jasmine", "ambergris", "cedar"], accords: ["warm spicy", "sweet", "amber", "woody"], rating: 4.6, reviews: 4102, review: "The compliment magnet. People will stop you on the street.", img: "https://fimgs.net/mdimg/perfume/375x500.33519.jpg", sillage: "strong" },
  { id: "4", name: "Flowerbomb", brand: "Viktor & Rolf", price: 135, pr: "$$", notes: ["jasmine", "rose", "orchid", "patchouli", "vanilla"], accords: ["floral", "sweet", "powdery", "warm spicy"], rating: 4.2, reviews: 3891, review: "A floral explosion that settles into something warm and cozy.", img: "https://fimgs.net/mdimg/perfume/375x500.12286.jpg", sillage: "moderate" },
  { id: "5", name: "Chance Eau Tendre", brand: "Chanel", price: 160, pr: "$$", notes: ["grapefruit", "jasmine", "white musk", "hyacinth"], accords: ["floral", "fresh", "citrus", "musky"], rating: 4.1, reviews: 2103, review: "Effortlessly chic \u2014 a white tee and gold jewelry in scent form.", img: "https://fimgs.net/mdimg/perfume/375x500.42579.jpg", sillage: "soft" },
  { id: "6", name: "Good Girl", brand: "Carolina Herrera", price: 120, pr: "$$", notes: ["jasmine", "cocoa", "tuberose", "tonka bean", "coffee"], accords: ["sweet", "warm spicy", "floral", "gourmand"], rating: 4.3, reviews: 3456, review: "Sexy and sophisticated. The heel bottle is iconic.", img: "https://fimgs.net/mdimg/perfume/375x500.39212.jpg", sillage: "strong" },
  { id: "7", name: "Cloud", brand: "Ariana Grande", price: 44, pr: "$", notes: ["lavender blossom", "coconut", "praline", "vanilla", "cashmere wood"], accords: ["sweet", "musky", "warm spicy", "powdery"], rating: 4.4, reviews: 4567, review: "Smells way more expensive than it is. Dupe energy queen.", img: "https://fimgs.net/mdimg/perfume/375x500.52382.jpg", sillage: "moderate" },
  { id: "8", name: "Delina", brand: "Parfums de Marly", price: 310, pr: "$$$", notes: ["lychee", "peony", "rose", "vanilla", "musk"], accords: ["floral", "sweet", "fresh", "fruity"], rating: 4.5, reviews: 2987, review: "Princess energy in a bottle. Feminine, soft, unforgettable.", img: "https://fimgs.net/mdimg/perfume/375x500.42584.jpg", sillage: "moderate" },
  { id: "9", name: "Brazilian Bum Bum Cream", brand: "Sol de Janeiro", price: 78, pr: "$", notes: ["pistachio", "salted caramel", "jasmine", "sandalwood"], accords: ["sweet", "warm spicy", "gourmand", "tropical"], rating: 4.3, reviews: 1890, review: "Beach vacation vibes year-round. Sweet but not cloying.", img: "https://fimgs.net/mdimg/perfume/375x500.50448.jpg", sillage: "moderate" },
  { id: "10", name: "La Vie Est Belle", brand: "Lanc\u00f4me", price: 115, pr: "$$", notes: ["iris", "praline", "vanilla", "patchouli", "blackcurrant"], accords: ["sweet", "gourmand", "powdery", "warm spicy"], rating: 4.2, reviews: 5234, review: "A warm hug in perfume form. Classic for a reason.", img: "https://fimgs.net/mdimg/perfume/375x500.17774.jpg", sillage: "moderate" },
  { id: "11", name: "Glossier You", brand: "Glossier", price: 69, pr: "$", notes: ["iris", "pink pepper", "ambrox", "white musk", "ambrette"], accords: ["musky", "warm spicy", "powdery", "fresh"], rating: 4.0, reviews: 1567, review: "The 'your skin but better' of perfumes.", img: "https://fimgs.net/mdimg/perfume/375x500.45044.jpg", sillage: "soft" },
  { id: "12", name: "J'adore", brand: "Dior", price: 155, pr: "$$", notes: ["ylang-ylang", "rose", "jasmine", "tuberose"], accords: ["floral", "fresh", "warm", "fruity"], rating: 4.3, reviews: 4321, review: "Timeless. Your mom wore it, you'll wear it, your daughter will too.", img: "https://fimgs.net/mdimg/perfume/375x500.203.jpg", sillage: "moderate" },
  { id: "13", name: "Kayali Vanilla 28", brand: "Kayali", price: 98, pr: "$", notes: ["vanilla orchid", "brown sugar", "tonka bean", "amber", "musk"], accords: ["sweet", "vanilla", "gourmand", "warm spicy"], rating: 4.4, reviews: 2345, review: "If vanilla had a luxury upgrade, this is it.", img: "https://fimgs.net/mdimg/perfume/375x500.52927.jpg", sillage: "moderate" },
  { id: "14", name: "Libre", brand: "Yves Saint Laurent", price: 138, pr: "$$", notes: ["lavender", "orange blossom", "vanilla", "musk", "cedar"], accords: ["floral", "warm spicy", "aromatic", "amber"], rating: 4.4, reviews: 3678, review: "Gender-fluid energy. Lavender + vanilla is chef's kiss.", img: "https://fimgs.net/mdimg/perfume/375x500.56756.jpg", sillage: "strong" },
  { id: "15", name: "Burberry Her", brand: "Burberry", price: 108, pr: "$$", notes: ["dark berries", "jasmine", "violet", "musk", "amber"], accords: ["fruity", "sweet", "floral", "gourmand"], rating: 4.2, reviews: 2156, review: "Berry-licious. Sweet without being juvenile.", img: "https://fimgs.net/mdimg/perfume/375x500.50498.jpg", sillage: "moderate" },
  { id: "16", name: "Cheirosa 71", brand: "Sol de Janeiro", price: 78, pr: "$", notes: ["caramelized vanilla", "sandalwood", "toasted macadamia"], accords: ["gourmand", "sweet", "warm", "tropical"], rating: 4.3, reviews: 1245, review: "Warm, yummy, and totally addictive.", img: "https://fimgs.net/mdimg/perfume/375x500.73889.jpg", sillage: "soft" },
  { id: "17", name: "Coco Mademoiselle", brand: "Chanel", price: 165, pr: "$$", notes: ["orange", "jasmine", "rose", "patchouli", "vetiver", "vanilla", "musk"], accords: ["floral", "citrus", "fresh spicy", "warm"], rating: 4.5, reviews: 6789, review: "The most sophisticated thing you can spray on yourself.", img: "https://fimgs.net/mdimg/perfume/375x500.611.jpg", sillage: "strong" },
  { id: "18", name: "Not a Perfume", brand: "Juliette Has a Gun", price: 95, pr: "$", notes: ["ambroxan", "cetalox"], accords: ["musky", "woody", "amber", "clean"], rating: 4.0, reviews: 1876, review: "Minimalist and magnetic. One molecule and it's magic.", img: "https://fimgs.net/mdimg/perfume/375x500.13185.jpg", sillage: "soft" },
  { id: "19", name: "Mon Guerlain", brand: "Guerlain", price: 124, pr: "$$", notes: ["lavender", "jasmine", "vanilla", "sandalwood", "iris"], accords: ["warm spicy", "powdery", "vanilla", "floral"], rating: 4.2, reviews: 2890, review: "Elegant and understated. Lavender-vanilla heaven.", img: "https://fimgs.net/mdimg/perfume/375x500.40906.jpg", sillage: "moderate" },
  { id: "20", name: "Daisy", brand: "Marc Jacobs", price: 88, pr: "$", notes: ["strawberry", "violet", "jasmine", "gardenia", "musk"], accords: ["floral", "fresh", "fruity", "musky"], rating: 4.1, reviews: 3456, review: "Fresh, girly, and easygoing. The ultimate first perfume.", img: "https://fimgs.net/mdimg/perfume/375x500.4945.jpg", sillage: "soft" },
];
