-- Whifff: Seed data — 20 perfumes from mock database
-- Run after schema.sql in Supabase SQL Editor

INSERT INTO perfumes (name, brand, notes_all, accords, rating, review_count, top_review, price_usd, price_range, sillage, image_url, popularity_score) VALUES
  ('Miss Dior Blooming Bouquet', 'Dior',
   ARRAY['peony','rose','white musk','damask rose'],
   ARRAY['floral','fresh','powdery','musky'],
   4.3, 2847, 'Like walking through a garden in spring — elegant without trying too hard.',
   110, '$$', 'soft', 'https://fimgs.net/mdimg/perfume/375x500.25808.jpg',
   4.3 * LN(2847 + 1)),

  ('Black Opium', 'Yves Saint Laurent',
   ARRAY['coffee','vanilla','white flowers','cedar'],
   ARRAY['warm spicy','sweet','vanilla','gourmand'],
   4.5, 5621, 'Addictive and bold — confidence in a bottle.',
   142, '$$', 'strong', 'https://fimgs.net/mdimg/perfume/375x500.25324.jpg',
   4.5 * LN(5621 + 1)),

  ('Baccarat Rouge 540', 'Maison Francis Kurkdjian',
   ARRAY['saffron','jasmine','ambergris','cedar'],
   ARRAY['warm spicy','sweet','amber','woody'],
   4.6, 4102, 'The compliment magnet. People will stop you on the street.',
   325, '$$$', 'strong', 'https://fimgs.net/mdimg/perfume/375x500.33519.jpg',
   4.6 * LN(4102 + 1)),

  ('Flowerbomb', 'Viktor & Rolf',
   ARRAY['jasmine','rose','orchid','patchouli','vanilla'],
   ARRAY['floral','sweet','powdery','warm spicy'],
   4.2, 3891, 'A floral explosion that settles into something warm and cozy.',
   135, '$$', 'moderate', 'https://fimgs.net/mdimg/perfume/375x500.12286.jpg',
   4.2 * LN(3891 + 1)),

  ('Chance Eau Tendre', 'Chanel',
   ARRAY['grapefruit','jasmine','white musk','hyacinth'],
   ARRAY['floral','fresh','citrus','musky'],
   4.1, 2103, 'Effortlessly chic — a white tee and gold jewelry in scent form.',
   160, '$$', 'soft', 'https://fimgs.net/mdimg/perfume/375x500.42579.jpg',
   4.1 * LN(2103 + 1)),

  ('Good Girl', 'Carolina Herrera',
   ARRAY['jasmine','cocoa','tuberose','tonka bean','coffee'],
   ARRAY['sweet','warm spicy','floral','gourmand'],
   4.3, 3456, 'Sexy and sophisticated. The heel bottle is iconic.',
   120, '$$', 'strong', 'https://fimgs.net/mdimg/perfume/375x500.39212.jpg',
   4.3 * LN(3456 + 1)),

  ('Cloud', 'Ariana Grande',
   ARRAY['lavender blossom','coconut','praline','vanilla','cashmere wood'],
   ARRAY['sweet','musky','warm spicy','powdery'],
   4.4, 4567, 'Smells way more expensive than it is. Dupe energy queen.',
   44, '$', 'moderate', 'https://fimgs.net/mdimg/perfume/375x500.52382.jpg',
   4.4 * LN(4567 + 1)),

  ('Delina', 'Parfums de Marly',
   ARRAY['lychee','peony','rose','vanilla','musk'],
   ARRAY['floral','sweet','fresh','fruity'],
   4.5, 2987, 'Princess energy in a bottle. Feminine, soft, unforgettable.',
   310, '$$$', 'moderate', 'https://fimgs.net/mdimg/perfume/375x500.42584.jpg',
   4.5 * LN(2987 + 1)),

  ('Brazilian Bum Bum Cream', 'Sol de Janeiro',
   ARRAY['pistachio','salted caramel','jasmine','sandalwood'],
   ARRAY['sweet','warm spicy','gourmand','tropical'],
   4.3, 1890, 'Beach vacation vibes year-round. Sweet but not cloying.',
   78, '$', 'moderate', 'https://fimgs.net/mdimg/perfume/375x500.50448.jpg',
   4.3 * LN(1890 + 1)),

  ('La Vie Est Belle', 'Lancôme',
   ARRAY['iris','praline','vanilla','patchouli','blackcurrant'],
   ARRAY['sweet','gourmand','powdery','warm spicy'],
   4.2, 5234, 'A warm hug in perfume form. Classic for a reason.',
   115, '$$', 'moderate', 'https://fimgs.net/mdimg/perfume/375x500.17774.jpg',
   4.2 * LN(5234 + 1)),

  ('Glossier You', 'Glossier',
   ARRAY['iris','pink pepper','ambrox','white musk','ambrette'],
   ARRAY['musky','warm spicy','powdery','fresh'],
   4.0, 1567, 'The ''your skin but better'' of perfumes.',
   69, '$', 'soft', 'https://fimgs.net/mdimg/perfume/375x500.45044.jpg',
   4.0 * LN(1567 + 1)),

  ('J''adore', 'Dior',
   ARRAY['ylang-ylang','rose','jasmine','tuberose'],
   ARRAY['floral','fresh','warm','fruity'],
   4.3, 4321, 'Timeless. Your mom wore it, you''ll wear it, your daughter will too.',
   155, '$$', 'moderate', 'https://fimgs.net/mdimg/perfume/375x500.203.jpg',
   4.3 * LN(4321 + 1)),

  ('Kayali Vanilla 28', 'Kayali',
   ARRAY['vanilla orchid','brown sugar','tonka bean','amber','musk'],
   ARRAY['sweet','vanilla','gourmand','warm spicy'],
   4.4, 2345, 'If vanilla had a luxury upgrade, this is it.',
   98, '$', 'moderate', 'https://fimgs.net/mdimg/perfume/375x500.52927.jpg',
   4.4 * LN(2345 + 1)),

  ('Libre', 'Yves Saint Laurent',
   ARRAY['lavender','orange blossom','vanilla','musk','cedar'],
   ARRAY['floral','warm spicy','aromatic','amber'],
   4.4, 3678, 'Gender-fluid energy. Lavender + vanilla is chef''s kiss.',
   138, '$$', 'strong', 'https://fimgs.net/mdimg/perfume/375x500.56756.jpg',
   4.4 * LN(3678 + 1)),

  ('Burberry Her', 'Burberry',
   ARRAY['dark berries','jasmine','violet','musk','amber'],
   ARRAY['fruity','sweet','floral','gourmand'],
   4.2, 2156, 'Berry-licious. Sweet without being juvenile.',
   108, '$$', 'moderate', 'https://fimgs.net/mdimg/perfume/375x500.50498.jpg',
   4.2 * LN(2156 + 1)),

  ('Cheirosa 71', 'Sol de Janeiro',
   ARRAY['caramelized vanilla','sandalwood','toasted macadamia'],
   ARRAY['gourmand','sweet','warm','tropical'],
   4.3, 1245, 'Warm, yummy, and totally addictive.',
   78, '$', 'soft', 'https://fimgs.net/mdimg/perfume/375x500.73889.jpg',
   4.3 * LN(1245 + 1)),

  ('Coco Mademoiselle', 'Chanel',
   ARRAY['orange','jasmine','rose','patchouli','vetiver','vanilla','musk'],
   ARRAY['floral','citrus','fresh spicy','warm'],
   4.5, 6789, 'The most sophisticated thing you can spray on yourself.',
   165, '$$', 'strong', 'https://fimgs.net/mdimg/perfume/375x500.611.jpg',
   4.5 * LN(6789 + 1)),

  ('Not a Perfume', 'Juliette Has a Gun',
   ARRAY['ambroxan','cetalox'],
   ARRAY['musky','woody','amber','clean'],
   4.0, 1876, 'Minimalist and magnetic. One molecule and it''s magic.',
   95, '$', 'soft', 'https://fimgs.net/mdimg/perfume/375x500.13185.jpg',
   4.0 * LN(1876 + 1)),

  ('Mon Guerlain', 'Guerlain',
   ARRAY['lavender','jasmine','vanilla','sandalwood','iris'],
   ARRAY['warm spicy','powdery','vanilla','floral'],
   4.2, 2890, 'Elegant and understated. Lavender-vanilla heaven.',
   124, '$$', 'moderate', 'https://fimgs.net/mdimg/perfume/375x500.40906.jpg',
   4.2 * LN(2890 + 1)),

  ('Daisy', 'Marc Jacobs',
   ARRAY['strawberry','violet','jasmine','gardenia','musk'],
   ARRAY['floral','fresh','fruity','musky'],
   4.1, 3456, 'Fresh, girly, and easygoing. The ultimate first perfume.',
   88, '$', 'soft', 'https://fimgs.net/mdimg/perfume/375x500.4945.jpg',
   4.1 * LN(3456 + 1));
